//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ReputationMessageType.msg.
//

#ifndef __REPUTATIONMESSAGETYPE_M_H
#define __REPUTATIONMESSAGETYPE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

/**
 * Enum generated from <tt>ReputationMessageType.msg:16</tt> by opp_msgtool.
 * <pre>
 * enum ReputationMessageType
 * {
 *     VOTE = 0;
 *     ASK_REPUTATION = 1;
 *     SEND_REPUTATION = 2;
 * 
 *     // 0 send a reputation vote from a peer | 1 ask for last reputation | 2 send reputation 
 * }
 * </pre>
 */
enum ReputationMessageType {
    VOTE = 0,
    ASK_REPUTATION = 1,
    SEND_REPUTATION = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReputationMessageType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReputationMessageType& e) { int n; b->unpack(n); e = static_cast<ReputationMessageType>(n); }


namespace omnetpp {


}  // namespace omnetpp

#endif // ifndef __REPUTATIONMESSAGETYPE_M_H

